version: '3'
services:
  db:
    image: mongo:4.2
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db

  web:
    image: node:14
    container_name: node_app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    working_dir: /app
    command: npm start
    depends_on:
      - db

  test:
    image: postman/newman:latest
    container_name: newman_test
    volumes:
      - .:/etc/newman
    command: ["run", "your-postman-collection.json", "--environment", "your-environment.json"]
    depends_on:
      - web

volumes:
  db_data:
